version: "3"

volumes:
  app:

services:
  banco:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  app:
    build:
      context: .
      args:
        PROFILES: docker
    ports:
      - 8080:8080
    depends_on:
      banco:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://banco:3306/goldvisionapi?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    volumes:
      - "./goldvision-credentials.json:/app/goldvision-credentials.json"
      - "./.env:/app/.env"